# Generated by Django 5.0.4 on 2024-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('idnum', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='std',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
